config/routes.rb
Rails.application.routes.draw do
    devise_for :owners
  	root 'places#index'
	resources :places do 
		resources :comments, only: [:create, :destroy]
	end
	resources :categories, only: [:show, :index]	
	#get 'places/new', to: 'places#new'
	#get 'places', to:'places#index'
	#get 'places/:id', to:'places#show', as: "place"
	#post 'places', to: 'places#create'
	#get 'places/:id/edit', to: 'places#edit' as: "edit_place"
	#patch 'places/:id', to: 'places#update'
	#delete 'places/:id', to: 'places#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :places
end

app/models/comment.rb
class Comment < ApplicationRecord
	validates :body, length: {minimum: 5}
	belongs_to :place
	belongs_to :owner
end

app/models/owner.rb
class Owner < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :places 
  has_many :comments, dependent: :destroy

  before_destroy :assign_to_first_owner
  private

    def assign_to_first_owner
        ideas.update_all(owner_id: Owner.first.id)
    end	
end

app/models/place.rb
class Place < ApplicationRecord
	validates :name, presence:true, length: {minimum:2}
	validates :address, presence:true, length: { minimum:8 }
	validates :established_at, presence:true
	validates :phone_number, presence:true
	validates :contact_mail, presence:true
	validates :city, presence:true
	
	
	belongs_to :category
	has_many :comments, dependent: :destroy
	belongs_to :owner
	
	private

    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
	before_action :load_sidebar_categories

  def load_sidebar_categories
    @sidebar_categories = Category.all
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	
  before_action :set_comment, only: [:destroy]
  before_action :authorize_owner!, only: [:destroy]

  def create
  		@comment = @place.comments.new(comment_params)
      @comment.owner = current_owner
   	if @comment.save
      redirect_to @place, notice: "Comment was saved."
    else
      redirect_to @place, notice: "Comment couldn't saved."
    end
   end

   def destroy
    @comment.destroy
    redirect_to @place, notice: "Comment was deleted."
   end
  


private 

  def comment_params
    params.require(:comment).permit(:body)
  end


  def set_comment
    @comment = Comment.find(params[:id])
  end

  def authorize_owner!
    redirect_to @place, notice: "Not authorized" unless @comment.owner_id == current_owner.id
  end

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
	before_action :authenticate_owner!, except: [:show, :index]
	before_action :set_place, only: [:show, :update, :edit, :destroy]
	before_action :authorize_owner!, only: [:edit, :update, :destroy]
	
	def new
		@place = Place.new
		load_categories
	end

	def index
		@places = Place.all
	end

	def show
		
	end

	def create
		@place = Place.new(place_params)
		@place = current_owner.places.new(place_params)
		
		if @place.save
			flash[:success] = 'Success'
			redirect_to place_path(@place)
		else
			load_categories
			render :new
		end
	end

	def edit
    	load_categories
  	end

  	def update
  		if @place.update(place_params)
  			redirect_to place_path(@place)
  		else
  			load_categories
  			render :edit
  		end
  	end

  	def destroy
		@place.destroy
		redirect_to places_path, notice: "Idea was deleted"
	end

	private

	def authorize_owner!
		redirect_to root_path, notice: "Not authorized" unless @place.owner_id == current_owner.id	
	end
	
	def place_params
		params.require(:place).permit(:name, :address, :established_at, :phone_number, :contact_mail, :city, :category_id)
    end	

    def set_place
    	@place = Place.find(params[:id]) 	
  	end	

  	def load_categories
  		@categories = Category.all.collect {|c| [c.name, c.id ] }
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/application/_flash.html.erb
<% if !flash.empty? %>
  <div id="flash">
    <% flash.keys.each do |k| %>
      <div class="<%= k %>">
        <%= flash[k] %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/categories/index.html.erb
<h1>Listing Categories</h1>

<% @categories.each do |c| %>
  <%= link_to c.name, category_path(c) %><br />
<% end %><br><br><br><br><br>

<%= link_to "Main Page", places_path %> <br>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

<% @category.places.each do |place| %>
  <b>ID </b><%= place.id %>
  <b>Title </b>
  <%= link_to place.name, place_path(place) %>
  <b>Description </b><%= place.description %><br>
<% end %><br><br><br><br>

<%= link_to "Categories", categories_path %> <br>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>



  <body>
  	<%= render "flash" %>
    <%= yield %>
    <hr>
      
    <% if current_owner.present? %>
      <%= link_to 'Logout', destroy_owner_session_path , method: :delete %><br>

    <%else %>
      <%= link_to 'Login', owner_session_path %><br>
      <%= link_to 'Sign in', new_owner_registration_path %><br>
      <%end %>
    
    

  </body>
</html>

app/views/places/_form.html.erb
<%= form_for @place do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, placeholder: 'name', class: "form-control input-sm" %><br>
  <br><br>
  <%= f.label :address %>
  <br>
  <%= f.text_area :address, placeholder: "address", rows: 10 %><br>
  <br>
  <%= f.label :established_at %>
  <br>
  <%= f.text_field :established_at, placeholder: 'established_at' %><br>
  <br>
   <%= f.label :phone_number %>
  <br>
  <%= f.text_field :phone_number, placeholder: 'phone_number' %><br>
  <br>
   <%= f.label :city %>
  <br>
  <%= f.text_field :city, placeholder: 'city' %><br>
  <br>
   <%= f.label :description %>
  <br>
  <%= f.text_field :description, placeholder: 'description' %><br>
  <br>
   <%= f.label :category_id %>
  <br>
  <%= f.select :category_id, @categories %>
  <br>
  <%= f.label :contact_mail %>
  <br>
  <%= f.text_field :contact_mail, placeholder:'contact_mail' %>
  <br>
  

  <br />
  <br />
  <br />
  
  <br>
  <%= f.submit 'Gonder' %>
<% end %>

app/views/places/edit.html.erb
<h1>Create a new place</h1>
<% if @place.errors.any? %>
	<h3><%= @place.errors.full_messages.join(", ") %></h3>
<% end %>

<%= render partial: "form" %>

app/views/places/index.html.erb
<html>
<b>Listing Places</b><br><br>
<% @places.each do |place| %>

<b>Name:</b>
<%= link_to place.name, place_path(place) %> <br>
<b>Address:</b><%= "#{place.address}"%><br>
<b>Phone Number:</b><%= place.phone_number%><br>
<b>Contact Mail:</b><%= place.contact_mail%><br>
<b>City:</b><%= place.city%><br>
<b>Description:</b><%= place.description%><br><br>
<% end %>

<%= link_to "Create a new place", new_place_path %> &nbsp;&nbsp;
<%= link_to "Categories", categories_path %> <br>

app/views/places/new.html.erb
<h1>Create a new place</h1>
<% if @place.errors.any? %>
	<h3><%= @place.errors.full_messages.join(", ") %></h3>
<% end %>

<%= render "form" %><br><br>
<%= link_to "Back to Main Page", places_path %> <br>

app/views/places/show.html.erb
<br>
<b>Id:</b><%= "#{@place.id}" %><br>
<b>Name:</b><%= "#{@place.name}" %><br>
<b>Address:</b><%= "#{@place.address}"%><br>
<b>Phone Number:</b><%= "#{@place.phone_number}"%><br>
<b>Contact Mail:</b><%= "#{@place.contact_mail}"%><br>
<b>City:</b><%= "#{@place.city}"%><br>
<b>Description:</b><%= "#{@place.description}"%><br>
<b>Category: </b><%= "#{@place.category.name}" %><br>
<b>Owner: </b><%= @place.owner.email %> | <%= @place.owner.id %><br />
<br/><br/>
<%= link_to "Back to place list", places_path %>

<br/>
<% if current_owner.present? and current_owner.id == @place.owner_id %>
<%= link_to "Edit place", edit_place_path(@place) %><br>
<%= link_to "Sil", place_path(@place), method: :delete %>
<br/><br/>
<% end %>

<h2>Listing Comments</h2>

<% @place.comments.each do |c| %>
  <small><%= comment.user.email %> says:</small> 
  <%= c.body %><br />
  <p>
        
     <% if current_owner.present? && c.owner_id == current_owner.id %>
     <small><%= link_to "Delete", place_comment_path(@place, comment), method: :delete %></small>
     <% end %>
     </p>
<% end %>
<br/><br/>
<% if current_owner.present? %>
<h3>Leave a comment</h3>
<%= form_for [@place, @place.comments.new] do |f| %>
<%= f.text_area :body, placeholder: "Enter a comment", rows: 10 %><br>	
<%= f.submit 'Gonder' %>
<% end %>
<% end %>